apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: manrodri/todo-api
      context: server
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .

    - image: manrodri/todo-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        infer:
          - "**/*.js"
#        manual:
#          - src: '**/*.js'
#            dest: .
